import re, math
from . import N, Q, Node, log

RE_DB = re.compile(r'(-?\d+\.\d+)dB')
def db(value: str) -> float:
    match = RE_DB.match(value)
    return float(match.group(1)) if match else 0.0
def db_int(value: str) -> int:
    return round(db(value))
def db_pc(value: str) -> float:
    return (db(value) + 120) / 120 * 100
def pc(value: str) -> float:
    return float(value[:-1])
RE_HZ = re.compile(r'(\d+\.\d+)Hz')
def hz(value: str) -> float:
    match = RE_HZ.match(value)
    return float(match.group(1)) if match else 0.0
def pc_hz(value: str) -> int:
    return round(10 ** ((pc(value) / 100) * (math.log10(20000) - math.log10(20)) + math.log10(20)))
def hz_pc(value: float) -> str:
    return (math.log10(float(value)) - math.log10(20)) / (math.log10(20000) - math.log10(20)) * 100
def onoff(value: str) -> bool:
    return value == 'On'

def sub(nodes: list[Node]):
    Q.extend([('sub', node.path) for node in nodes])
def unsub(nodes: list[Node]):
    Q.extend([('unsub', node.path) for node in nodes])
def loop(nodes: list):
    Q.extend([('asyncget', node.path) for node in nodes])

DEV = N['Node']['SV']['DeviceName']
PRE = N['Storage']['Presets']['SV']['CurrentPreset']
NAME = N['Storage']['Presets']['SV']['Name_13'] # TODO
CURR_PRE = N['Storage']['Presets']['SV']['CurrentPreset']

L_IN = N['Preset']['InputMeters']['SV']['LeftInput']
R_IN = N['Preset']['InputMeters']['SV']['RightInput']
L_IN_CLIP = N['Preset']['InputMeters']['SV']['LeftInputClip']
R_IN_CLIP = N['Preset']['InputMeters']['SV']['RightInputClip']

L_HIGH = N['Preset']['OutputMeters']['SV']['HighLeftOutput']
MUTE_L_HIGH = N['Preset']['OutputGains']['SV']['HighLeftOutputMute']
R_HIGH = N['Preset']['OutputMeters']['SV']['HighRightOutput']
MUTE_R_HIGH = N['Preset']['OutputGains']['SV']['HighRightOutputMute']
LMT_HIGH = N['Preset']['HighOutputsLimiter']['SV']['ThresholdMeter']
L_MID = N['Preset']['OutputMeters']['SV']['MidLeftOutput']
MUTE_L_MID = N['Preset']['OutputGains']['SV']['MidLeftOutputMute']
R_MID = N['Preset']['OutputMeters']['SV']['MidRightOutput']
MUTE_R_MID = N['Preset']['OutputGains']['SV']['MidRightOutputMute']
LMT_MID = N['Preset']['MidOutputsLimiter']['SV']['ThresholdMeter']
L_LOW = N['Preset']['OutputMeters']['SV']['LowLeftOutput']
MUTE_L_LOW = N['Preset']['OutputGains']['SV']['LowLeftOutputMute']
R_LOW = N['Preset']['OutputMeters']['SV']['LowRightOutput']
MUTE_R_LOW = N['Preset']['OutputGains']['SV']['LowRightOutputMute']
LMT_LOW = N['Preset']['LowOutputsLimiter']['SV']['ThresholdMeter']

# Subharmonic Synth
SH = N['Preset']['SubharmonicSynth']['SV']['Subharmonics']
SH_ = N['Preset']['SubharmonicSynth']['SV']['Subharmonics']['%']
SS = N['Preset']['SubharmonicSynth']['SV']['SubharmonicSynth']
SS_ = N['Preset']['SubharmonicSynth']['SV']['SubharmonicSynth']['%']
SS_24 = N['Preset']['SubharmonicSynth']['SV']['Synthesis Level 24-36Hz']
SS_24_ = N['Preset']['SubharmonicSynth']['SV']['Synthesis Level 24-36Hz']['%']
SS_36 = N['Preset']['SubharmonicSynth']['SV']['Synthesis Level 36-56Hz']
SS_36_ = N['Preset']['SubharmonicSynth']['SV']['Synthesis Level 36-56Hz']['%']
SS_LEVEL = N['Preset']['SubharmonicSynth']['SV']['SubSynthLevel']
SS_UPPER = N['Preset']['SubharmonicSynth']['SV']['UpperBandLevel']
SS_LOWER = N['Preset']['SubharmonicSynth']['SV']['LowerBandLevel']

# High Parametic EQ
PEQ_HIGH = N['Preset']['High Outputs PEQ']['SV']['ParametricEQ']
PEQ_HIGH_MANUAL = N['Preset']['High Outputs PEQ']['SV']['Manual']
PEQ_HIGH_AUTO = N['Preset']['High Outputs PEQ']['SV']['AutoEQ']
PEQ_HIGH_LO = N['Preset']['High Outputs PEQ']['SV']['Low Shelf']
PEQ_HIGH_HS = N['Preset']['High Outputs PEQ']['SV']['High Shelf']
PEQ_HIGH_FL = N['Preset']['High Outputs PEQ']['SV']['Flatten']
PEQ_HIGH_BELL = N['Preset']['High Outputs PEQ']['SV']['Bell']
PEQ_HIGH_BAND = [None] * 9
for i in range(1, 9):
    PEQ_HIGH_BAND[i] = {
        'type': N['Preset']['High Outputs PEQ']['SV'][f'Band_{i}_Type'],
        'q': N['Preset']['High Outputs PEQ']['SV'][f'Band_{i}_Q'],
        'gain': N['Preset']['High Outputs PEQ']['SV'][f'Band_{i}_Gain'],
        'freq': N['Preset']['High Outputs PEQ']['SV'][f'Band_{i}_Frequency']['%'],
    }

# Mid Parametic EQ
PEQ_MID = N['Preset']['Mid Outputs PEQ']['SV']['ParametricEQ']
PEQ_MID_MANUAL = N['Preset']['Mid Outputs PEQ']['SV']['Manual']
PEQ_MID_AUTO = N['Preset']['Mid Outputs PEQ']['SV']['AutoEQ']
PEQ_MID_LO = N['Preset']['Mid Outputs PEQ']['SV']['Low Shelf']
PEQ_MID_HS = N['Preset']['Mid Outputs PEQ']['SV']['High Shelf']
PEQ_MID_FL = N['Preset']['Mid Outputs PEQ']['SV']['Flatten']
PEQ_MID_BELL = N['Preset']['Mid Outputs PEQ']['SV']['Bell']
PEQ_MID_BAND = [None] * 9
for i in range(1, 9):
    PEQ_MID_BAND[i] = {
        'type': N['Preset']['Mid Outputs PEQ']['SV'][f'Band_{i}_Type'],
        'q': N['Preset']['Mid Outputs PEQ']['SV'][f'Band_{i}_Q'],
        'gain': N['Preset']['Mid Outputs PEQ']['SV'][f'Band_{i}_Gain'],
        'freq': N['Preset']['Mid Outputs PEQ']['SV'][f'Band_{i}_Frequency']['%'],
    }

# Low Parametic EQ
PEQ_LOW = N['Preset']['Low Outputs PEQ']['SV']['ParametricEQ']
PEQ_LOW_MANUAL = N['Preset']['Low Outputs PEQ']['SV']['Manual']
PEQ_LOW_AUTO = N['Preset']['Low Outputs PEQ']['SV']['AutoEQ']
PEQ_LOW_LO = N['Preset']['Low Outputs PEQ']['SV']['Low Shelf']
PEQ_LOW_HS = N['Preset']['Low Outputs PEQ']['SV']['High Shelf']
PEQ_LOW_FL = N['Preset']['Low Outputs PEQ']['SV']['Flatten']
PEQ_LOW_BELL = N['Preset']['Low Outputs PEQ']['SV']['Bell']
PEQ_LOW_BAND = [None] * 9
for i in range(1, 9):
    PEQ_LOW_BAND[i] = {
        'type': N['Preset']['Low Outputs PEQ']['SV'][f'Band_{i}_Type'],
        'q': N['Preset']['Low Outputs PEQ']['SV'][f'Band_{i}_Q'],
        'gain': N['Preset']['Low Outputs PEQ']['SV'][f'Band_{i}_Gain'],
        'freq': N['Preset']['Low Outputs PEQ']['SV'][f'Band_{i}_Frequency']['%'],
    }

# VAR = N['Node']['AT']['Class_Name']
# VAR = N['Node']['AT']['Instance_Name']
# VAR = N['Node']['AT']['Software_Version']
# VAR = N['Node']['SV']['HardwareVersion']
# VAR = N['Node']['SV']['HardwareVersion']['']
# VAR = N['Storage']['Presets']['SV']['CurrentPreset']['']
# VAR = N['Node']['Wizard']['SV']['WizardState']['']
# VAR = N['Node']['Wizard']['SV']['LevelAssistOutput']['']
# VAR = N['Node']['Config']['SV']['Command']['']
# VAR = N['Node']['Config']['SV']['Result']['']
# VAR = N['Node']['Config']['SV']['Progress']['']
# VAR = N['Node']['Config']['SV']['Command:Status']['']
# VAR = N['Storage']['Presets']['SV']['CurrentPreset']
# VAR = N['Storage']['Presets']['SV']['Changed']['']
# VAR = N['Node']['Wizard']['SV']['WizardState']
# VAR = N['Node']['Wizard']['SV']['LevelAssistOutput']
# VAR = N['Preset']['OutputGains']['SV']['LowLeftOutputMute']['']
# VAR = N['Preset']['OutputGains']['SV']['LowRightOutputMute']['']
# VAR = N['Preset']['OutputGains']['SV']['MidLeftOutputMute']['']
# VAR = N['Preset']['OutputGains']['SV']['MidRightOutputMute']['']
# VAR = N['Preset']['OutputGains']['SV']['HighLeftOutputMute']['']
# VAR = N['Preset']['OutputGains']['SV']['HighRightOutputMute']['']
# VAR = N['Preset']['Crossover']['AT']['NumBands']['']
# VAR = N['Preset']['Crossover']['AT']['MonoSub']['']
# VAR = N['Preset']['']
# VAR = N['Preset']['SignalGenerator']['SV']['Signal Generator']['']
# VAR = N['Preset']['Afs']['SV']['AFS']['']
# VAR = N['Preset']['StereoGEQ']['SV']['GraphicEQ']['']
# VAR = N['Preset']['LeftGEQ']['SV']['GraphicEQ']['']
# VAR = N['Preset']['RightGEQ']['SV']['GraphicEQ']['']
# VAR = N['Preset']['RoomEQ']['SV']['ParametricEQ']['']
# VAR = N['Preset']['SubharmonicSynth']['SV']['SubharmonicSynth']['']
# VAR = N['Preset']['Compressor']['SV']['Compressor']['']
# VAR = N['Preset']['Back Line Delay']['SV']['Delay']['']
# VAR = N['Preset']['High Outputs PEQ']['SV']['ParametricEQ']['']
# VAR = N['Preset']['High Outputs Limiter']['SV']['Limiter']['']
# VAR = N['Preset']['High Outputs Delay']['SV']['Delay']['']
# VAR = N['Preset']['Mid Outputs PEQ']['SV']['ParametricEQ']['']
# VAR = N['Preset']['Mid Outputs Limiter']['SV']['Limiter']['']
# VAR = N['Preset']['Mid Outputs Delay']['SV']['Delay']['']
# VAR = N['Preset']['Low Outputs PEQ']['SV']['ParametricEQ']['']
# VAR = N['Preset']['Low Outputs Limiter']['SV']['Limiter']['']
# VAR = N['Preset']['Low Outputs Delay']['SV']['Delay']['']
# VAR = N['Preset']['OutputMeters']['SV']['HighLeftOutput']['']
# VAR = N['Preset']['High Outputs Limiter']['SV']['ThresholdMeter']['']
# VAR = N['Preset']['OutputMeters']['SV']['HighRightOutput']['']
# VAR = N['Preset']['OutputMeters']['SV']['MidLeftOutput']['']
# VAR = N['Preset']['Mid Outputs Limiter']['SV']['ThresholdMeter']['']
# VAR = N['Preset']['OutputMeters']['SV']['MidRightOutput']['']
# VAR = N['Preset']['OutputMeters']['SV']['LowLeftOutput']['']
# VAR = N['Preset']['Low Outputs Limiter']['SV']['ThresholdMeter']['']
# VAR = N['Preset']['OutputMeters']['SV']['LowRightOutput']['']
# VAR = N['Preset']['InputMeters']['SV']['LeftInput']['']
# VAR = N['Preset']['InputMeters']['SV']['LeftInputClip']['']
# VAR = N['Preset']['InputMeters']['SV']['RightInput']['']
# VAR = N['Preset']['InputMeters']['SV']['RightInputClip']['']
# VAR = N['Storage']['Presets']['SV']['Name_']['']
# VAR = N['Storage']['Presets']['SV']['Changed']
# VAR = N['Preset']['OutputGains']['SV']['LowLeftOutputMute']
# VAR = N['Preset']['OutputGains']['SV']['LowRightOutputMute']
# VAR = N['Preset']['OutputGains']['SV']['MidLeftOutputMute']
# VAR = N['Preset']['OutputGains']['SV']['MidRightOutputMute']
# VAR = N['Preset']['OutputGains']['SV']['HighLeftOutputMute']
# VAR = N['Preset']['OutputGains']['SV']['HighRightOutputMute']
# VAR = N['Storage']['Presets']['SV']['Name_13']['']
# VAR = N['Preset']['Crossover']['AT']['NumBands']
# VAR = N['Preset']['Crossover']['AT']['MonoSub']
# VAR = N['Preset']
# VAR = N['Preset']['SignalGenerator']['SV']['Signal Generator']
# VAR = N['Preset']['Afs']['SV']['AFS']
# VAR = N['Preset']['StereoGEQ']['SV']['GraphicEQ']
# VAR = N['Preset']['RoomEQ']['SV']['ParametricEQ']
# VAR = N['Preset']['SubharmonicSynth']['SV']['SubharmonicSynth']
# VAR = N['Preset']['Compressor']['SV']['Compressor']
# VAR = N['Preset']['Back Line Delay']['SV']['Delay']
# VAR = N['Preset']['High Outputs PEQ']['SV']['ParametricEQ']
# VAR = N['Preset']['High Outputs Limiter']['SV']['Limiter']
# VAR = N['Preset']['High Outputs Delay']['SV']['Delay']
# VAR = N['Preset']['Mid Outputs PEQ']['SV']['ParametricEQ']
# VAR = N['Preset']['Mid Outputs Limiter']['SV']['Limiter']
# VAR = N['Preset']['Mid Outputs Delay']['SV']['Delay']
# VAR = N['Preset']['Low Outputs PEQ']['SV']['ParametricEQ']
# VAR = N['Preset']['Low Outputs Limiter']['SV']['Limiter']
# VAR = N['Preset']['Low Outputs Delay']['SV']['Delay']
# VAR = N['Preset']['High Outputs Limiter']['SV']['ThresholdMeter']
# VAR = N['Preset']['OutputMeters']['SV']['HighLeftOutput']
# VAR = N['Preset']['OutputMeters']['SV']['HighRightOutput']
# VAR = N['Preset']['OutputMeters']['SV']['MidLeftOutput']
# VAR = N['Preset']['OutputMeters']['SV']['MidRightOutput']
# VAR = N['Preset']['OutputMeters']['SV']['LowLeftOutput']
# VAR = N['Preset']['OutputMeters']['SV']['LowRightOutput']
# VAR = N['Preset']['InputMeters']['SV']['LeftInput']
# VAR = N['Preset']['InputMeters']['SV']['RightInput']
# VAR = N['Preset']['InputMeters']['SV']['LeftInputClip']
# VAR = N['Preset']['InputMeters']['SV']['RightInputClip']
# VAR = N['Preset']['Mid Outputs Limiter']['SV']['ThresholdMeter']
# VAR = N['Preset']['Low Outputs Limiter']['SV']['ThresholdMeter']
# VAR = N['Storage']['Presets']['SV']['Name_13']
# VAR = N['Node']['SV']['DeviceName']['']
# VAR = N['Node']['SV']['DeviceName']
# VAR = N['Preset']['SubharmonicSynth']['SV']['LowerBandLevel']['']
# VAR = N['Preset']['SubharmonicSynth']['SV']['UpperBandLevel']['']
# VAR = N['Preset']['SubharmonicSynth']['SV']['SubSynthLevel']['']
# VAR = N['Preset']['SubharmonicSynth']['SV']['Subharmonics']['']
# VAR = N['Preset']['SubharmonicSynth']['SV']['Subharmonics']['%']
# VAR = N['Preset']['SubharmonicSynth']['SV']['Synthesis Level 36-56Hz']['']
# VAR = N['Preset']['SubharmonicSynth']['SV']['Synthesis Level 36-56Hz']['%']
# VAR = N['Preset']['SubharmonicSynth']['SV']['Synthesis Level 24-36Hz']['']
# VAR = N['Preset']['SubharmonicSynth']['SV']['Synthesis Level 24-36Hz']['%']
# VAR = N['Preset']['SubharmonicSynth']['SV']['SubSynthLevel']
# VAR = N['Preset']['SubharmonicSynth']['SV']['LowerBandLevel']
# VAR = N['Preset']['SubharmonicSynth']['SV']['UpperBandLevel']
# VAR = N['Preset']['SubharmonicSynth']['SV']['Subharmonics']
# VAR = N['Preset']['SubharmonicSynth']['SV']['Synthesis Level 36-56Hz']
# VAR = N['Preset']['SubharmonicSynth']['SV']['Synthesis Level 24-36Hz']
# VAR = N['Preset']['Afs']['SV']['LiveLiftEnable']['']
# VAR = N['Preset']['Afs']['SV']['ClearAll']['']
# VAR = N['Preset']['Afs']['SV']['ClearLive']['']
# VAR = N['Preset']['Afs']['SV']['MaxFixedFilters']['']
# VAR = N['Preset']['Afs']['SV']['MaxFixedFilters']['%']
# VAR = N['Preset']['Afs']['SV']['LiftTime']['']
# VAR = N['Preset']['Afs']['SV']['LiftTime']['%']
# VAR = N['Preset']['Afs']['SV']['ContentMode']['']
# VAR = N['Preset']['Afs']['SV']['ContentMode']['Max']['']
# VAR = N['Preset']['Afs']['SV']['ContentMode']['Min']['']
# VAR = N['Preset']['Afs']['SV']['ContentMode']['EN']['']
# VAR = N['Preset']['Afs']['SV']['FilterMode']['']
# VAR = N['Preset']['Afs']['SV']['FilterMode']['Max']['']
# VAR = N['Preset']['Afs']['SV']['FilterMode']['Min']['']
# VAR = N['Preset']['Afs']['SV']['FilterMode']['EN']['']
# VAR = N['Preset']['Afs']['SV']['Band_12_Q']['']
# VAR = N['Preset']['Afs']['SV']['Band_12_Gain']['']
# VAR = N['Preset']['Afs']['SV']['Band_12_Frequency']['']
# VAR = N['Preset']['Afs']['SV']['Band_11_Q']['']
# VAR = N['Preset']['Afs']['SV']['Band_11_Gain']['']
# VAR = N['Preset']['Afs']['SV']['Band_11_Frequency']['']
# VAR = N['Preset']['Afs']['SV']['Band_10_Q']['']
# VAR = N['Preset']['Afs']['SV']['Band_10_Gain']['']
# VAR = N['Preset']['Afs']['SV']['Band_10_Frequency']['']
# VAR = N['Preset']['Afs']['SV']['Band_9_Q']['']
# VAR = N['Preset']['Afs']['SV']['Band_9_Gain']['']
# VAR = N['Preset']['Afs']['SV']['Band_9_Frequency']['']
# VAR = N['Preset']['Afs']['SV']['Band_8_Q']['']
# VAR = N['Preset']['Afs']['SV']['Band_8_Gain']['']
# VAR = N['Preset']['Afs']['SV']['Band_8_Frequency']['']
# VAR = N['Preset']['Afs']['SV']['Band_7_Q']['']
# VAR = N['Preset']['Afs']['SV']['Band_7_Gain']['']
# VAR = N['Preset']['Afs']['SV']['Band_7_Frequency']['']
# VAR = N['Preset']['Afs']['SV']['Band_6_Q']['']
# VAR = N['Preset']['Afs']['SV']['Band_6_Gain']['']
# VAR = N['Preset']['Afs']['SV']['Band_6_Frequency']['']
# VAR = N['Preset']['Afs']['SV']['Band_5_Q']['']
# VAR = N['Preset']['Afs']['SV']['Band_5_Gain']['']
# VAR = N['Preset']['Afs']['SV']['Band_5_Frequency']['']
# VAR = N['Preset']['Afs']['SV']['Band_4_Q']['']
# VAR = N['Preset']['Afs']['SV']['Band_4_Gain']['']
# VAR = N['Preset']['Afs']['SV']['Band_4_Frequency']['']
# VAR = N['Preset']['Afs']['SV']['Band_3_Q']['']
# VAR = N['Preset']['Afs']['SV']['Band_3_Gain']['']
# VAR = N['Preset']['Afs']['SV']['Band_3_Frequency']['']
# VAR = N['Preset']['Afs']['SV']['Band_2_Q']['']
# VAR = N['Preset']['Afs']['SV']['Band_2_Gain']['']
# VAR = N['Preset']['Afs']['SV']['Band_2_Frequency']['']
# VAR = N['Preset']['Afs']['SV']['Band_1_Q']['']
# VAR = N['Preset']['Afs']['SV']['Band_1_Gain']['']
# VAR = N['Preset']['Afs']['SV']['Band_1_Frequency']['']
# VAR = N['Preset']['Afs']['SV']['LiveLiftEnable']
# VAR = N['Preset']['Afs']['SV']['ClearAll']
# VAR = N['Preset']['Afs']['SV']['ClearLive']
# VAR = N['Preset']['Afs']['SV']['MaxFixedFilters']
# VAR = N['Preset']['Afs']['SV']['LiftTime']
# VAR = N['Preset']['Afs']['SV']['ContentMode']
# VAR = N['Preset']['Afs']['SV']['ContentMode']['Max']
# VAR = N['Preset']['Afs']['SV']['ContentMode']['Min']
# VAR = N['Preset']['Afs']['SV']['ContentMode']['EN']
# VAR = N['Preset']['Afs']['SV']['FilterMode']
# VAR = N['Preset']['Afs']['SV']['FilterMode']['Max']
# VAR = N['Preset']['Afs']['SV']['FilterMode']['Min']
# VAR = N['Preset']['Afs']['SV']['FilterMode']['EN']
# VAR = N['Preset']['Afs']['SV']['Band_12_Q']
# VAR = N['Preset']['Afs']['SV']['Band_12_Gain']
# VAR = N['Preset']['Afs']['SV']['Band_12_Frequency']
# VAR = N['Preset']['Afs']['SV']['Band_11_Q']
# VAR = N['Preset']['Afs']['SV']['Band_11_Gain']
# VAR = N['Preset']['Afs']['SV']['Band_11_Frequency']
# VAR = N['Preset']['Afs']['SV']['Band_10_Q']
# VAR = N['Preset']['Afs']['SV']['Band_10_Gain']
# VAR = N['Preset']['Afs']['SV']['Band_10_Frequency']
# VAR = N['Preset']['Afs']['SV']['Band_9_Q']
# VAR = N['Preset']['Afs']['SV']['Band_9_Gain']
# VAR = N['Preset']['Afs']['SV']['Band_9_Frequency']
# VAR = N['Preset']['Afs']['SV']['Band_8_Q']
# VAR = N['Preset']['Afs']['SV']['Band_8_Gain']
# VAR = N['Preset']['Afs']['SV']['Band_8_Frequency']
# VAR = N['Preset']['Afs']['SV']['Band_7_Q']
# VAR = N['Preset']['Afs']['SV']['Band_7_Gain']
# VAR = N['Preset']['Afs']['SV']['Band_7_Frequency']
# VAR = N['Preset']['Afs']['SV']['Band_6_Q']
# VAR = N['Preset']['Afs']['SV']['Band_6_Gain']
# VAR = N['Preset']['Afs']['SV']['Band_6_Frequency']
# VAR = N['Preset']['Afs']['SV']['Band_5_Q']
# VAR = N['Preset']['Afs']['SV']['Band_5_Gain']
# VAR = N['Preset']['Afs']['SV']['Band_5_Frequency']
# VAR = N['Preset']['Afs']['SV']['Band_4_Q']
# VAR = N['Preset']['Afs']['SV']['Band_4_Gain']
# VAR = N['Preset']['Afs']['SV']['Band_4_Frequency']
# VAR = N['Preset']['Afs']['SV']['Band_3_Q']
# VAR = N['Preset']['Afs']['SV']['Band_3_Gain']
# VAR = N['Preset']['Afs']['SV']['Band_3_Frequency']
# VAR = N['Preset']['Afs']['SV']['Band_2_Q']
# VAR = N['Preset']['Afs']['SV']['Band_2_Gain']
# VAR = N['Preset']['Afs']['SV']['Band_2_Frequency']
# VAR = N['Preset']['Afs']['SV']['Band_1_Q']
# VAR = N['Preset']['Afs']['SV']['Band_1_Gain']
# VAR = N['Preset']['Afs']['SV']['Band_1_Frequency']
# VAR = N['Preset']['Crossover']['SV']['Band_1_LPType']['']
# VAR = N['Preset']['Crossover']['SV']['Band_1_LPType']['Max']['']
# VAR = N['Preset']['Crossover']['SV']['Band_1_LPType']['Min']['']
# VAR = N['Preset']['Crossover']['SV']['Band_1_LPType']['EN']['']
# VAR = N['Preset']['Crossover']['SV']['Band_1_HPType']['']
# VAR = N['Preset']['Crossover']['SV']['Band_1_HPType']['Max']['']
# VAR = N['Preset']['Crossover']['SV']['Band_1_HPType']['Min']['']
# VAR = N['Preset']['Crossover']['SV']['Band_1_HPType']['EN']['']
# VAR = N['Preset']['Crossover']['SV']['Band_1_Polarity']['']
# VAR = N['Preset']['Crossover']['SV']['Inverted']['']
# VAR = N['Preset']['Crossover']['SV']['Normal']['']
# VAR = N['Preset']['Crossover']['SV']['Band_1_Gain']['']
# VAR = N['Preset']['Crossover']['SV']['Band_1_Gain']['%']
# VAR = N['Preset']['Crossover']['SV']['Band_1_LPFrequency']['']
# VAR = N['Preset']['Crossover']['SV']['Band_1_LPFrequency']['%']
# VAR = N['Preset']['Crossover']['SV']['Band_1_HPFrequency']['']
# VAR = N['Preset']['Crossover']['SV']['Band_1_HPFrequency']['%']
# VAR = N['Preset']['Crossover']['SV']['Band_3_LPFrequency']['']
# VAR = N['Preset']['Crossover']['SV']['Band_3_HPFrequency']['']
# VAR = N['Preset']['Crossover']['SV']['Band_3_Gain']['']
# VAR = N['Preset']['Crossover']['SV']['Band_2_LPFrequency']['']
# VAR = N['Preset']['Crossover']['SV']['Band_2_HPFrequency']['']
# VAR = N['Preset']['Crossover']['SV']['Band_2_Gain']['']
# VAR = N['Preset']['Crossover']['SV']['Band_2_HPType']['']
# VAR = N['Preset']['Crossover']['SV']['Band_2_LPType']['']
# VAR = N['Preset']['Crossover']['SV']['Band_2_Polarity']['']
# VAR = N['Preset']['Crossover']['SV']['Band_3_HPType']['']
# VAR = N['Preset']['Crossover']['SV']['Band_3_LPType']['']
# VAR = N['Preset']['Crossover']['SV']['Band_3_Polarity']['']
# VAR = N['Preset']['Crossover']['SV']['Band_1_LPType']
# VAR = N['Preset']['Crossover']['SV']['Band_1_LPType']['Max']
# VAR = N['Preset']['Crossover']['SV']['Band_1_LPType']['Min']
# VAR = N['Preset']['Crossover']['SV']['Band_1_LPType']['EN']
# VAR = N['Preset']['Crossover']['SV']['Band_1_HPType']
# VAR = N['Preset']['Crossover']['SV']['Band_1_HPType']['Max']
# VAR = N['Preset']['Crossover']['SV']['Band_1_HPType']['Min']
# VAR = N['Preset']['Crossover']['SV']['Band_1_HPType']['EN']
# VAR = N['Preset']['Crossover']['SV']['Band_1_Polarity']
# VAR = N['Preset']['Crossover']['SV']['Band_1_Gain']
# VAR = N['Preset']['Crossover']['SV']['Band_1_LPFrequency']
# VAR = N['Preset']['Crossover']['SV']['Band_1_HPFrequency']
# VAR = N['Preset']['Crossover']['SV']['Band_3_LPFrequency']
# VAR = N['Preset']['Crossover']['SV']['Band_3_HPFrequency']
# VAR = N['Preset']['Crossover']['SV']['Band_3_Gain']
# VAR = N['Preset']['Crossover']['SV']['Band_2_LPFrequency']
# VAR = N['Preset']['Crossover']['SV']['Band_2_HPFrequency']
# VAR = N['Preset']['Crossover']['SV']['Band_2_Gain']
# VAR = N['Preset']['Crossover']['SV']['Band_2_HPType']
# VAR = N['Preset']['Crossover']['SV']['Band_2_LPType']
# VAR = N['Preset']['Crossover']['SV']['Band_2_Polarity']
# VAR = N['Preset']['Crossover']['SV']['Band_3_HPType']
# VAR = N['Preset']['Crossover']['SV']['Band_3_LPType']
# VAR = N['Preset']['Crossover']['SV']['Band_3_Polarity']
# VAR = N['Preset']['Crossover']['SV']['Band_2_LPType']['Max']['']
# VAR = N['Preset']['Crossover']['SV']['Band_2_LPType']['Min']['']
# VAR = N['Preset']['Crossover']['SV']['Band_2_LPType']['EN']['']
# VAR = N['Preset']['Crossover']['SV']['Band_2_HPType']['Max']['']
# VAR = N['Preset']['Crossover']['SV']['Band_2_HPType']['Min']['']
# VAR = N['Preset']['Crossover']['SV']['Band_2_HPType']['EN']['']
# VAR = N['Preset']['Crossover']['SV']['Band_2_Gain']['%']
# VAR = N['Preset']['Crossover']['SV']['Band_2_LPFrequency']['%']
# VAR = N['Preset']['Crossover']['SV']['Band_2_HPFrequency']['%']
# VAR = N['Preset']['Crossover']['SV']['Band_2_LPType']['Max']
# VAR = N['Preset']['Crossover']['SV']['Band_2_LPType']['Min']
# VAR = N['Preset']['Crossover']['SV']['Band_2_LPType']['EN']
# VAR = N['Preset']['Crossover']['SV']['Band_2_HPType']['Max']
# VAR = N['Preset']['Crossover']['SV']['Band_2_HPType']['Min']
# VAR = N['Preset']['Crossover']['SV']['Band_2_HPType']['EN']
# VAR = N['Preset']['Crossover']['SV']['Band_3_LPType']['Max']['']
# VAR = N['Preset']['Crossover']['SV']['Band_3_LPType']['Min']['']
# VAR = N['Preset']['Crossover']['SV']['Band_3_LPType']['EN']['']
# VAR = N['Preset']['Crossover']['SV']['Band_3_HPType']['Max']['']
# VAR = N['Preset']['Crossover']['SV']['Band_3_HPType']['Min']['']
# VAR = N['Preset']['Crossover']['SV']['Band_3_HPType']['EN']['']
# VAR = N['Preset']['Crossover']['SV']['Band_3_Gain']['%']
# VAR = N['Preset']['Crossover']['SV']['Band_3_LPFrequency']['%']
# VAR = N['Preset']['Crossover']['SV']['Band_3_HPFrequency']['%']
# VAR = N['Preset']['Crossover']['SV']['Band_3_LPType']['Max']
# VAR = N['Preset']['Crossover']['SV']['Band_3_LPType']['Min']
# VAR = N['Preset']['Crossover']['SV']['Band_3_LPType']['EN']
# VAR = N['Preset']['Crossover']['SV']['Band_3_HPType']['Max']
# VAR = N['Preset']['Crossover']['SV']['Band_3_HPType']['Min']
# VAR = N['Preset']['Crossover']['SV']['Band_3_HPType']['EN']
# VAR = N['Preset']['High Outputs Limiter']['SV']['GainReductionMeter']['']
# VAR = N['Preset']['High Outputs Limiter']['SV']['OverEasy']['']
# VAR = N['Preset']['High Outputs Limiter']['SV']['Threshold']['']
# VAR = N['Preset']['High Outputs Limiter']['SV']['Threshold']['%']
# VAR = N['Preset']['High Outputs Limiter']['SV']['OverEasy']['%']
# VAR = N['Preset']['High Outputs Limiter']['SV']['OverEasy']
# VAR = N['Preset']['High Outputs Limiter']['SV']['Threshold']
# VAR = N['Preset']['High Outputs Limiter']['SV']['GainReductionMeter']
# VAR = N['Preset']['Mid Outputs Limiter']['SV']['GainReductionMeter']['']
# VAR = N['Preset']['Mid Outputs Limiter']['SV']['OverEasy']['']
# VAR = N['Preset']['Mid Outputs Limiter']['SV']['Threshold']['']
# VAR = N['Preset']['Mid Outputs Limiter']['SV']['Threshold']['%']
# VAR = N['Preset']['Mid Outputs Limiter']['SV']['OverEasy']['%']
# VAR = N['Preset']['Mid Outputs Limiter']['SV']['OverEasy']
# VAR = N['Preset']['Mid Outputs Limiter']['SV']['Threshold']
# VAR = N['Preset']['Mid Outputs Limiter']['SV']['GainReductionMeter']
# VAR = N['Preset']['Low Outputs Limiter']['SV']['GainReductionMeter']['']
# VAR = N['Preset']['Low Outputs Limiter']['SV']['OverEasy']['']
# VAR = N['Preset']['Low Outputs Limiter']['SV']['Threshold']['']
# VAR = N['Preset']['Low Outputs Limiter']['SV']['Threshold']['%']
# VAR = N['Preset']['Low Outputs Limiter']['SV']['OverEasy']['%']
# VAR = N['Preset']['Low Outputs Limiter']['SV']['OverEasy']
# VAR = N['Preset']['Low Outputs Limiter']['SV']['Threshold']
# VAR = N['Preset']['Low Outputs Limiter']['SV']['GainReductionMeter']
# VAR = N['Preset']['Low Outputs Delay']['SV']['Amount']['']
# VAR = N['Preset']['Low Outputs Delay']['SV']['Amount']['%']
# VAR = N['Preset']['Mid Outputs Delay']['SV']['Amount']['']
# VAR = N['Preset']['Mid Outputs Delay']['SV']['Amount']['%']
# VAR = N['Preset']['High Outputs Delay']['SV']['Amount']['']
# VAR = N['Preset']['High Outputs Delay']['SV']['Amount']['%']
# VAR = N['Preset']['Low Outputs Delay']['SV']['Amount']
# VAR = N['Preset']['Mid Outputs Delay']['SV']['Amount']
# VAR = N['Preset']['High Outputs Delay']['SV']['Amount']
# VAR = N['Preset']['StereoGEQ']['SV']['Manual']['']
# VAR = N['Preset']['StereoGEQ']['SV']['DJ']['']
# VAR = N['Preset']['StereoGEQ']['SV']['PerformanceVenue']['']
# VAR = N['Preset']['StereoGEQ']['SV']['Speech']['']
# VAR = N['Preset']['StereoGEQ']['SV']['MyBand']['']
# VAR = N['Preset']['StereoGEQ']['SV']['Flat']['']
# VAR = N['Preset']['StereoGEQ']['SV']['QuickCurve']['']
# VAR = N['Preset']['StereoGEQ']['SV']['20 Hz']['']
# VAR = N['Preset']['StereoGEQ']['SV']['25 Hz']['']
# VAR = N['Preset']['StereoGEQ']['SV']['31']
# VAR = N['Preset']['StereoGEQ']['SV']['40 Hz']['']
# VAR = N['Preset']['StereoGEQ']['SV']['50 Hz']['']
# VAR = N['Preset']['StereoGEQ']['SV']['63 Hz']['']
# VAR = N['Preset']['StereoGEQ']['SV']['80 Hz']['']
# VAR = N['Preset']['StereoGEQ']['SV']['100 Hz']['']
# VAR = N['Preset']['StereoGEQ']['SV']['125 Hz']['']
# VAR = N['Preset']['StereoGEQ']['SV']['160 Hz']['']
# VAR = N['Preset']['StereoGEQ']['SV']['200 Hz']['']
# VAR = N['Preset']['StereoGEQ']['SV']['250 Hz']['']
# VAR = N['Preset']['StereoGEQ']['SV']['315 Hz']['']
# VAR = N['Preset']['StereoGEQ']['SV']['400 Hz']['']
# VAR = N['Preset']['StereoGEQ']['SV']['500 Hz']['']
# VAR = N['Preset']['StereoGEQ']['SV']['630 Hz']['']
# VAR = N['Preset']['StereoGEQ']['SV']['800 Hz']['']
# VAR = N['Preset']['StereoGEQ']['SV']['1']
# VAR = N['Preset']['StereoGEQ']['SV']['2']
# VAR = N['Preset']['StereoGEQ']['SV']['3']
# VAR = N['Preset']['StereoGEQ']['SV']['4']
# VAR = N['Preset']['StereoGEQ']['SV']['5']
# VAR = N['Preset']['StereoGEQ']['SV']['6']
# VAR = N['Preset']['StereoGEQ']['SV']['8']
# VAR = N['Preset']['StereoGEQ']['SV']['10']
# VAR = N['Preset']['StereoGEQ']['SV']['12']
# VAR = N['Preset']['StereoGEQ']['SV']['16']
# VAR = N['Preset']['StereoGEQ']['SV']['20']
# VAR = N['Preset']['StereoGEQ']['SV']['QuickCurve']
# VAR = N['Preset']['StereoGEQ']['SV']['20 Hz']
# VAR = N['Preset']['StereoGEQ']['SV']['25 Hz']
# VAR = N['Preset']['StereoGEQ']['SV']['40 Hz']
# VAR = N['Preset']['StereoGEQ']['SV']['50 Hz']
# VAR = N['Preset']['StereoGEQ']['SV']['63 Hz']
# VAR = N['Preset']['StereoGEQ']['SV']['80 Hz']
# VAR = N['Preset']['StereoGEQ']['SV']['100 Hz']
# VAR = N['Preset']['StereoGEQ']['SV']['125 Hz']
# VAR = N['Preset']['StereoGEQ']['SV']['160 Hz']
# VAR = N['Preset']['StereoGEQ']['SV']['200 Hz']
# VAR = N['Preset']['StereoGEQ']['SV']['250 Hz']
# VAR = N['Preset']['StereoGEQ']['SV']['315 Hz']
# VAR = N['Preset']['StereoGEQ']['SV']['400 Hz']
# VAR = N['Preset']['StereoGEQ']['SV']['500 Hz']
# VAR = N['Preset']['StereoGEQ']['SV']['630 Hz']
# VAR = N['Preset']['StereoGEQ']['SV']['800 Hz']
# VAR = N['Node']['SV']['Reboot']['']
# VAR = N['Node']['AT']['Software_Version']['']
# VAR = N['Node']['BLUX']['SV']['SampleRate']['']
# VAR = N['Node']['SV']['Reboot']
# VAR = N['Storage']['Presets']['SV']['Name_1']['']
# VAR = N['Storage']['Presets']['SV']['Name_2']['']
# VAR = N['Storage']['Presets']['SV']['Name_3']['']
# VAR = N['Storage']['Presets']['SV']['Name_4']['']
# VAR = N['Storage']['Presets']['SV']['Name_5']['']
# VAR = N['Storage']['Presets']['SV']['Name_6']['']
# VAR = N['Storage']['Presets']['SV']['Name_7']['']
# VAR = N['Storage']['Presets']['SV']['Name_8']['']
# VAR = N['Storage']['Presets']['SV']['Name_9']['']
# VAR = N['Storage']['Presets']['SV']['Name_10']['']
# VAR = N['Storage']['Presets']['SV']['Name_11']['']
# VAR = N['Storage']['Presets']['SV']['Name_12']['']
# VAR = N['Storage']['Presets']['SV']['Name_14']['']
# VAR = N['Storage']['Presets']['SV']['Name_15']['']
# VAR = N['Storage']['Presets']['SV']['Name_16']['']
# VAR = N['Storage']['Presets']['SV']['Name_1']
# VAR = N['Storage']['Presets']['SV']['Name_2']
# VAR = N['Storage']['Presets']['SV']['Name_3']
# VAR = N['Storage']['Presets']['SV']['Name_4']
# VAR = N['Storage']['Presets']['SV']['Name_5']
# VAR = N['Storage']['Presets']['SV']['Name_6']
# VAR = N['Storage']['Presets']['SV']['Name_7']
# VAR = N['Storage']['Presets']['SV']['Name_8']
# VAR = N['Storage']['Presets']['SV']['Name_9']
# VAR = N['Storage']['Presets']['SV']['Name_10']
# VAR = N['Storage']['Presets']['SV']['Name_11']
# VAR = N['Storage']['Presets']['SV']['Name_12']
# VAR = N['Storage']['Presets']['SV']['Name_14']
# VAR = N['Storage']['Presets']['SV']['Name_15']
# VAR = N['Storage']['Presets']['SV']['Name_16']
# VAR = N['Storage']['Presets']['SV']['Name_17']['']
# VAR = N['Storage']['Presets']['SV']['Name_18']['']
# VAR = N['Storage']['Presets']['SV']['Name_19']['']
# VAR = N['Storage']['Presets']['SV']['Name_20']['']
# VAR = N['Storage']['Presets']['SV']['Name_17']
# VAR = N['Storage']['Presets']['SV']['Name_18']
# VAR = N['Storage']['Presets']['SV']['Name_19']
# VAR = N['Storage']['Presets']['SV']['Name_20']
# VAR = N['Node']['Wizard']['SV']['WizardEvent']['']
# VAR = N['Node']['Wizard']['SV']['WizardEvent']
# VAR = N['Node']['Wizard']['SV']['WizardRunAll']['']
# VAR = N['Preset']['LevelAssist']['SV']['AdjustAmountMeter']['']
# VAR = N['Node']['Wizard']['SV']['WizardRunAll']

